### ISSUE TITLE
If your file has a "#" in it, it will not show in your Presentation when you use a folder. 

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-image#169] opened 2018-08-07 19:43 UTC
### What is the expected behavior?
Regardless of the name of the file, it should show in your Presentation.

### What is the actual behavior?
If your file has a #, it will not show in the Presentation if you are playing this for a folder. If you link to the file directly, it shows.

### What steps can be taken to replicate the problem?
1. Add the Image Widget to a folder that has a file with a # in the title.
2. Notice in the Presentation, that file will not show in the image rotation.
3. Notice again if you add the image using a direct link to the file, it will show.

**Comment by stulees** [comment] 2018-08-08 16:57
@robb-price I'm unable to recreate the issue when testing a folder of images and one file has a # in it. The image is downloaded and gets displayed successfully. 

Can you provide a presentation where you see the issue occur? Thanks

**Comment by stulees** [comment] 2018-08-08 20:59
@sheadarlison I've confirmed with @robb-price that this is not an issue with the Widget and is happening due to the already open Trash issue - https://github.com/Rise-Vision/rise-launcher-electron/issues/756

Closing this issue.

**Closed by stulees** 2018-08-08 20:59 UTC
