### ISSUE TITLE
When network resource is blocked, widgets don't load a proper error message.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-image#153] opened 2018-06-01 14:50 UTC
**NOTE THAT THIS AFFECTS ALL WIDGETS NOT JUST IMAGE**

**How to recreate**

Access apps.risevision.com on a network with rvashow2.appspot.com blocked.
Configure a Widget.

**What happens**
Widget doesn't fully load and has no error message to tell the user what's wrong. See attached image.
![inconclusive](https://user-images.githubusercontent.com/8458926/40847120-1d15de78-6581-11e8-8d04-545f156e784f.png)

**What should happen**
Widget should not load. Error message should appear that says "Sorry, we're having trouble accessing rvashow2.appspot.com, which is a required resource. Please resolve this with your network team and try again".

**Comment by btfrise** [comment] 2018-06-01 14:50
![](https://github.trello.services/images/mini-trello-icon.png) [[Ticket Blocked] Issue 153 When network resource is blocked, widgets don't load a proper error message.](https://trello.com/c/10UEiNFl/8087-ticket-blocked-issue-153-when-network-resource-is-blocked-widgets-dont-load-a-proper-error-message)

**Comment by stulees** [comment] 2018-06-01 15:28
@btfrise @sheadarlison @ezequielc This appears to be an Apps issue as it involves Editor and not specific to Image widget or any other widget. Can we move to the appropriate Apps repo for this issue?

**Comment by sheadarlison** [comment] 2018-06-01 15:45
@alex-deaconu could you please recap your SoS comments re. this issue and why you think it's a widget problem and what we should to to fix it.

**Comment by ezequielc** [comment] 2018-06-01 15:48
@stulees We covered this in SoS this morning. It seems the issue is with the Widget Settings, which doesn't load properly and throws an angular error due to the network block.
The suggested actions where to:
1. Handle the error properly so it doesn't break the UI;
2. Move the blocked resource (gadgets RPC js, I think) to the widget itself or use it from a domain which would not likely to be blocked, like apps.risevision.com

Thanks
@sheadarlison @alex-deaconu fyi

**Comment by alex-deaconu** [comment] 2018-06-01 15:51
@ezequielc that is correct, however apps.risevision.com does not actually host the file in question.

To confirm, this is the dependency in question: https://github.com/Rise-Vision/widget-image/blob/master/src/settings.html#L182. If moving it to the dist for the Widget (you can add the Viewer project and get that file via bower), you can consider pointing to preview.risevision.com or viewer.risevision.com.

Thanks.

**Comment by stulees** [comment] 2018-06-01 16:00
@alex-deaconu @ezequielc Thanks for clarifying.

If it is just a matter of that gadgets RPC dependency that is the problem, then we fortunately have a quick solution. That gadgets file is already bundled in Widgets as a part of the build via this [script](https://github.com/Rise-Vision/widget-image/blob/master/include-deps.sh) and is targeted on the widget side, see here - https://github.com/Rise-Vision/widget-image/blob/master/src/widget.html#L45 . 

I think we overlooked doing the same for Settings but we can change that. @sheadarlison FYI

**Comment by alex-deaconu** [comment] 2018-06-01 16:31
@stulees interesting, but it seems quite complicated. Why not just bundle via bower? Thanks.

**Comment by stulees** [comment] 2018-06-01 16:42
@alex-deaconu We set it up this way on Delivery a while ago for enabling the widgets to run offline in Player. The Viewer project/bower approach never came up. The script is very small and runs [post widget build](https://github.com/Rise-Vision/widget-image/blob/master/package.json#L8), not overly complicated.

It will be a small update to each widget Settings html to just change the path for gadgets file to be relative. Cheers

**Comment by btfrise** [comment] 2018-06-01 21:18
@stulees We discussed this at standup and they determined it was a content issue as it affects all Widgets. I will wait to hear back, but this was initially logged with apps.

**Comment by btfrise** [comment] 2018-06-01 21:19
Please let me know what is determined and where I should log this.

**Comment by btfrise** [comment] 2018-06-01 21:20
All of the comments didn't load for me. I see that this is staying with Content. Thanks.

**Comment by santiagonoguez** [comment] 2018-07-03 16:01
@btfrise This has been corrected for all widgets that present the error. The settings and widget should now work even if rvashow2 is blocked. 

Please validate this is the case.

Note that the issue may still appear on browsers that have cached previous component pages, but if you see that happening clearing the browser cache should help.

FYI @sheadarlison @stulees @ezequielc @alex-deaconu

**Comment by santiagonoguez** [comment] 2018-07-04 13:48
Closing this issue. I validated in all affected widget types.

**Closed by santiagonoguez** 2018-07-04 13:48 UTC
Labels: bug
